instrumentation:
  root: '.'
  excludes:
    - 'container.js'
    - 'app/Application.js'
    - 'interfaces/http/server.js'
    - '**/*.spec.js'
reporting:
  dir: './coverage'
  reports:
    - html
    - lcov
